const ACCESS_TOKEN = "ACCESS_TOKEN";
const ACCESS_TOKEN_VALUE = "7|htUAeeIawQUtf2NXZdBlKrU0G9gnlRTPA0tXVJKF"
const LANGUAGE = "LANGUAGE"
const INDONESIA = "id"
const ENGLISH = "en"
export { ACCESS_TOKEN_VALUE, LANGUAGE, INDONESIA, ENGLISH };
